---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ehc586-test-flask-deployment
    labels:
        username: ehc586
        env: test
        app: ehc586-test-flask
spec:
    replicas: 2
    selector:
        matchLabels:
            app: ehc586-test-flask
    template:
        metadata:
            labels:
                app: ehc586-test-flask
        spec:
            containers:
                - name: ehc586-test-flask-deployment
                  imagePullPolicy: Always
                  image: etchi17/k8s:hw6
                  command: ['python3', 'app.py']
                  ports:
                  - name: http
                    containerPort: 5000
